
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package RefalInterpritator;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EXTERN = 4;
  public static final int SEMICOLON = 2;
  public static final int RBRACE = 7;
  public static final int RPAREN = 10;
  public static final int EQUAL = 8;
  public static final int RCHEVRON = 13;
  public static final int NAME = 11;
  public static final int VARIABLE = 16;
  public static final int QUOTEDSTRING = 14;
  public static final int LPAREN = 9;
  public static final int COLON = 3;
  public static final int LBRACE = 6;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int ENTRY = 5;
  public static final int error = 1;
  public static final int LCHEVRON = 12;
  public static final int INTEGER_LITERAL = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COLON",
  "EXTERN",
  "ENTRY",
  "LBRACE",
  "RBRACE",
  "EQUAL",
  "LPAREN",
  "RPAREN",
  "NAME",
  "LCHEVRON",
  "RCHEVRON",
  "QUOTEDSTRING",
  "INTEGER_LITERAL",
  "VARIABLE",
  "COMMA"
  };
}

