
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package VerificatorInterpritator;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ATLEAST = 14;
  public static final int MANY = 13;
  public static final int SEMICOLON = 7;
  public static final int OR = 8;
  public static final int RPAREN = 3;
  public static final int EQUAL = 10;
  public static final int RCHEVRON = 6;
  public static final int NAME = 4;
  public static final int VARIABLE = 11;
  public static final int QUOTEDSTRING = 15;
  public static final int LPAREN = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LCHEVRON = 5;
  public static final int INTEGER_LITERAL = 16;
  public static final int VAREQUAL = 9;
  public static final int METAVARIABLE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "NAME",
  "LCHEVRON",
  "RCHEVRON",
  "SEMICOLON",
  "OR",
  "VAREQUAL",
  "EQUAL",
  "VARIABLE",
  "METAVARIABLE",
  "MANY",
  "ATLEAST",
  "QUOTEDSTRING",
  "INTEGER_LITERAL"
  };
}

